"""Unit tests for package.py. Run from the workspace root:

uv run --no-project --with pytest --with trimesh --with numpy \
    python -m pytest scripts/tools/robot-web-models -q
"""

import json
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import package as pk  # noqa: E402
import resolve as rs  # noqa: E402

TINY_URDF = """<?xml version="1.0" ?>
<!-- autogenerated from /Users/nobody/ws/install/share/tiny.urdf.xacro -->
<robot name="tiny">
  <link name="base">
    <visual><geometry><mesh filename="package://tiny_description/meshes/Base.STL"/></geometry></visual>
    <collision><geometry><mesh filename="package://tiny_description/meshes/base_col.stl"/></geometry></collision>
  </link>
  <link name="arm">
    <visual><geometry><mesh filename="package://tiny_description/meshes/arm.stl" scale="0.001 0.001 0.001"/></geometry></visual>
    <collision><geometry><box size="1 1 1"/></geometry></collision>
  </link>
  <link name="tip"/>
  <joint name="j1" type="revolute"><parent link="base"/><child link="arm"/>
    <limit lower="-1.5" upper="1.5" effort="1" velocity="1"/></joint>
  <joint name="j2" type="continuous"><parent link="arm"/><child link="tip"/></joint>
  <joint name="j3" type="fixed"><parent link="base"/><child link="tip"/></joint>
  <joint name="j4" type="prismatic"><parent link="base"/><child link="tip"/>
    <limit lower="0" upper="0.1"/><mimic joint="j1" multiplier="2" offset="0.5"/></joint>
  <ros2_control name="mock" type="system"><hardware><plugin>mock_components/GenericSystem</plugin></hardware></ros2_control>
  <transmission name="t1"/>
</robot>
"""

VISUAL_URIS = [
    "package://tiny_description/meshes/Base.STL",
    "package://tiny_description/meshes/arm.stl",
]


def test_visual_mesh_uris_skips_collision():
    assert pk.visual_mesh_uris(TINY_URDF) == VISUAL_URIS


def test_rewrite_urdf():
    text, info = pk.rewrite_urdf(TINY_URDF, pk.mesh_names(VISUAL_URIS))
    assert "<collision" not in text
    assert "<ros2_control" not in text
    assert "<transmission" not in text
    assert "package://" not in text
    assert "/Users/" not in text
    assert 'filename="meshes/base.glb"' in text
    assert 'filename="meshes/arm.glb" scale="0.001 0.001 0.001"' in text
    assert info["links"] == 3
    assert info["meshes"] == ["arm.glb", "base.glb"]
    assert info["joints"] == [
        {"name": "j1", "type": "revolute", "lower": -1.5, "upper": 1.5},
        {"name": "j2", "type": "continuous"},
        {
            "name": "j4",
            "type": "prismatic",
            "lower": 0.0,
            "upper": 0.1,
            "mimic": {"joint": "j1", "multiplier": 2.0, "offset": 0.5},
        },
    ]


def test_rewrite_urdf_rejects_unknown_mesh():
    with pytest.raises(ValueError):
        pk.rewrite_urdf(TINY_URDF, {})


def test_mesh_names_hash_basename_collisions():
    names = pk.mesh_names(
        [
            "package://a/left/link.stl",
            "package://a/right/LINK.stl",
            "package://a/other.STL",
        ]
    )
    assert names["package://a/other.STL"] == "other.glb"
    left, right = names["package://a/left/link.stl"], names["package://a/right/LINK.stl"]
    assert left != right
    assert left.startswith("link-") and left.endswith(".glb")
    assert right.startswith("link-") and right.endswith(".glb")
    assert len(left) == len("link-") + 8 + len(".glb")


def test_mesh_names_are_worker_safe():
    uris = [
        "package://p/__Weird..Name-.STL",
        "package://p/-_-.stl",
        "package://p/...stl",
        "package://p/Link \u00e4 (1).stl",
        "package://p/" + "x" * 300 + ".stl",
        "package://p/a/same.stl",
        "package://p/b/SAME.STL",
    ]
    names = pk.mesh_names(uris)
    assert len(set(names.values())) == len(uris)
    for name in names.values():
        assert pk.worker_safe(f"meshes/{name}"), name
        assert pk.worker_safe(name), name
    assert names["package://p/__Weird..Name-.STL"] == "weird.name-.glb"
    assert names["package://p/-_-.stl"].startswith("mesh-")
    assert names["package://p/...stl"] == "stl.glb"
    assert names["package://p/Link \u00e4 (1).stl"] == "link_1_.glb"
    assert len(names["package://p/" + "x" * 300 + ".stl"]) == pk.MAX_STEM + len(".glb")
    assert names["package://p/a/same.stl"] != names["package://p/b/SAME.STL"]


def test_package_files_rejects_names_the_worker_drops():
    manifest = {"variants": {"v": {"urdf": "-v.urdf"}}, "meshes": {"ok.glb": {}}}
    with pytest.raises(ValueError):
        pk.package_files(manifest)
    manifest = {"variants": {"v": {"urdf": "v.urdf"}}, "meshes": {"a..b.glb": {}}}
    with pytest.raises(ValueError):
        pk.package_files(manifest)


def test_resolve_variant_guard():
    rs.check_variants({"key": "x", "variants": ["a"]}, None)
    rs.check_variants({"key": "x", "variants": ["a", "b"]}, "preset")
    rs.check_variants({"key": "x", "variants": ["a"], "aliases": {"b": "a"}}, None)
    with pytest.raises(SystemExit):
        rs.check_variants({"key": "x", "variants": ["a", "b"]}, None)
    with pytest.raises(SystemExit):
        rs.check_variants({"key": "x", "variants": ["a"], "aliases": {"b": "c"}}, None)
    g1 = next(r for r in rs.ROBOTS if r["key"] == "g1_d")
    assert g1["variants"] == ["g1_d"] and g1["aliases"] == {"g1_29dof_rev_1_0": "g1_d"}
    for entry in rs.ROBOTS:
        for alias in entry.get("aliases", {}):
            assert pk.worker_safe(f"{alias}.urdf")
        for variant in entry["variants"]:
            assert pk.worker_safe(f"{variant}.urdf")


def test_assert_clean_json():
    pk.assert_clean_json({"a": [1, "x", {"b": "pkg/rel.stl"}]})
    with pytest.raises(ValueError):
        pk.assert_clean_json({"a": None})
    with pytest.raises(ValueError):
        pk.assert_clean_json({"a": ["/Users/nobody/x"]})
    with pytest.raises(ValueError):
        pk.assert_clean_json({"a": "package://pkg/x"})


def _cube_stl(path):
    import trimesh

    cube = trimesh.creation.box(extents=(0.1, 0.2, 0.3))
    cube.export(path)
    return cube


def test_convert_mesh_round_trip(tmp_path):
    import trimesh

    src = str(tmp_path / "cube.stl")
    cube = _cube_stl(src)
    raw = str(tmp_path / "glb" / "cube.raw.glb")
    out = str(tmp_path / "glb" / "cube.glb")
    shipped = pk.convert_mesh(src, raw, out, optimize=False, force=True)
    assert shipped == raw
    back = trimesh.load(shipped, force="mesh")
    assert len(back.faces) == len(cube.faces) == 12
    assert back.extents == pytest.approx(cube.extents)
    assert pk.glb_info(shipped) == {"triangles": 12, "extensions_required": []}


FAKE_OPTIMIZE = [sys.executable, "-c", "import shutil, sys; shutil.copyfile(sys.argv[2], sys.argv[3])"]


def _mtimes(*paths):
    return tuple(os.stat(p).st_mtime_ns for p in paths)


def test_convert_mesh_cache_stamps(tmp_path, monkeypatch):
    import trimesh

    src = str(tmp_path / "part.stl")
    _cube_stl(src)
    raw = str(tmp_path / "glb" / "part.raw.glb")
    out = str(tmp_path / "glb" / "part.glb")
    convert = lambda s, force=False: pk.convert_mesh(s, raw, out, optimize=True, force=force, command=FAKE_OPTIMIZE)

    assert convert(src) == out
    assert os.path.isfile(pk.stamp_path(raw)) and os.path.isfile(pk.stamp_path(out))
    first = _mtimes(raw, out)

    # Same source: both entries current, nothing rebuilds.
    convert(src)
    assert _mtimes(raw, out) == first

    # Same path and mtime, different bytes: the size in the stamp catches it.
    src_mtime = os.stat(src).st_mtime_ns
    sphere = trimesh.creation.icosphere(subdivisions=1)
    sphere.export(src)
    os.utime(src, ns=(src_mtime, src_mtime))
    convert(src)
    assert len(trimesh.load(raw, force="mesh").faces) == len(sphere.faces)

    # Same name retargeted to another file: the source path in the stamp catches it.
    src2 = str(tmp_path / "other" / "part.stl")
    os.makedirs(os.path.dirname(src2))
    _cube_stl(src2)
    convert(src2)
    assert len(trimesh.load(raw, force="mesh").faces) == 12
    assert json.load(open(pk.stamp_path(raw)))["source"] == os.path.abspath(src2)

    # Changed optimize arguments: only the optimized entry rebuilds.
    before = _mtimes(raw, out)
    monkeypatch.setattr(pk, "OPTIMIZE_ARGS", pk.OPTIMIZE_ARGS + ["--changed"])
    convert(src2)
    after = _mtimes(raw, out)
    assert after[0] == before[0] and after[1] != before[1]
    assert json.load(open(pk.stamp_path(out)))["optimize_args"][-1] == "--changed"

    # --force rebuilds both.
    before = _mtimes(raw, out)
    convert(src2, force=True)
    after = _mtimes(raw, out)
    assert after[0] != before[0] and after[1] != before[1]


def test_package_all_shape(tmp_path):
    work = tmp_path / "work"
    out = tmp_path / "out"
    (work / "tiny").mkdir(parents=True)
    src = work / "meshes"
    src.mkdir()
    for name in ("Base.STL", "arm.stl", "base_col.stl"):
        _cube_stl(str(src / name))
    (work / "tiny" / "tiny.urdf.src").write_text(TINY_URDF)
    resolved = {
        "generated_at": "2026-01-01T00:00:00Z",
        "robots": {
            "tiny": {
                "label": "Tiny",
                "default_variant": "tiny",
                "variants": ["tiny"],
                "aliases": {"alias": "tiny"},
                "urdfs": {"tiny": "tiny/tiny.urdf.src"},
            }
        },
        "meshes": {
            f"package://tiny_description/meshes/{n}": {
                "path": str(src / n),
                "pkg": "tiny_description",
                "rel": f"meshes/{n}",
                "bytes": os.path.getsize(src / n),
            }
            for n in ("Base.STL", "arm.stl", "base_col.stl")
        },
    }
    (work / "resolved.json").write_text(json.dumps(resolved))
    # A stray file in the package dir must not survive: the tree equals the closed list.
    (out / "models" / "tiny" / "meshes").mkdir(parents=True)
    (out / "models" / "tiny" / "meshes" / "stale.glb").write_bytes(b"x")

    rows = pk.package_all(str(work), str(out), optimize=False)
    assert rows[0]["meshes"] == 2 and rows[0]["variants"] == 2

    robot_dir = out / "models" / "tiny"
    manifest = json.loads((robot_dir / "manifest.json").read_text())
    index = json.loads((out / "models" / "index.json").read_text())
    pk.assert_clean_json(manifest)
    pk.assert_clean_json(index)

    assert manifest["key"] == "tiny" and manifest["label"] == "Tiny"
    assert manifest["default_variant"] == "tiny"
    assert set(manifest["variants"]) == {"tiny", "alias"}
    assert manifest["variants"]["alias"]["alias_of"] == "tiny"
    assert manifest["variants"]["alias"]["urdf"] == "alias.urdf"
    assert manifest["variants"]["tiny"]["links"] == 3
    assert [j["name"] for j in manifest["variants"]["tiny"]["joints"]] == ["j1", "j2", "j4"]
    assert set(manifest["meshes"]) == {"base.glb", "arm.glb"}
    assert manifest["meshes"]["base.glb"]["source"] == "tiny_description/meshes/Base.STL"
    assert manifest["meshes"]["base.glb"]["triangles"] == 12
    assert manifest["total_bytes"] == sum(
        os.path.getsize(robot_dir / f) for f in ("tiny.urdf", "alias.urdf", "meshes/base.glb", "meshes/arm.glb")
    )

    assert index["source"] and index["generated_at"].endswith("Z")
    (model,) = index["models"]
    assert model["key"] == "tiny"
    assert model["variants"] == ["tiny", "alias"]
    assert model["default_variant"] == "tiny"
    assert sorted(model["files"]) == sorted(
        ["manifest.json", "tiny.urdf", "alias.urdf", "meshes/base.glb", "meshes/arm.glb"]
    )
    for name in model["files"]:
        assert pk.WORKER_FILE_RE.match(name) and ".." not in name, name

    on_disk = sorted(
        os.path.relpath(os.path.join(base, f), robot_dir)
        for base, _d, files in os.walk(robot_dir)
        for f in files
    )
    assert on_disk == sorted(model["files"])
    assert (robot_dir / "tiny.urdf").read_text() == (robot_dir / "alias.urdf").read_text()
