#!/usr/bin/env bash
# Shared narration helpers for the fm_ros2 scripts. Sourced, never executed.
#
# This file is the only copy. install.sh runs curl-piped before the clone exists,
# so it fetches this file and evals it (see load_lib there) rather than carrying
# duplicates that drift.

# Status line under a step header — one place to restyle later.
item() { echo "$1"; }

# Newest release tag of a checkout (vN.N.N-style, highest by version sort), or
# empty when the repo has none. The appliance release channel keys off this:
# installers pin to it and appliance-update.sh converges to it.
latest_release_tag() {  # dir
  git -C "$1" tag -l 'v[0-9]*' --sort=-v:refname 2>/dev/null | head -1
}

# Move a checkout onto its newest release tag — the appliance install-time half
# of the release channel (appliance-update.sh is the converge-over-time half).
# Refuses to move a repo with local changes, and leaves an untagged repo where
# it is; both are warned, never fatal. Tag tips are fetched shallow when the
# repo itself is shallow, so a --depth 1 appliance clone stays lean.
pin_release() {  # dir
  local dir="$1" tag
  [ -d "$dir/.git" ] || return 0
  local -a depth=()
  [ -f "$(git -C "$dir" rev-parse --git-dir)/shallow" ] && depth=(--depth 1)
  git -C "$dir" fetch --quiet --force ${depth[@]+"${depth[@]}"} origin \
    '+refs/tags/*:refs/tags/*' 2>/dev/null || true
  tag="$(latest_release_tag "$dir")"
  if [ -z "$tag" ]; then
    item "WARNING: $(basename "$dir") has no release tag yet — staying on its current checkout"
    return 0
  fi
  if [ -n "$(git -C "$dir" status --porcelain --untracked-files=no 2>/dev/null)" ]; then
    item "WARNING: $(basename "$dir") has local changes — not moving it to $tag"
    return 0
  fi
  [ "$(git -C "$dir" rev-parse HEAD)" = "$(git -C "$dir" rev-parse "$tag^{commit}")" ] && return 0
  item "pinning $(basename "$dir") to release $tag ..."
  git -C "$dir" -c advice.detachedHead=false checkout --quiet "$tag"
}

# Report package checkouts that landed under the kebab repo slug (src/fm-robot)
# instead of the workspace's snake_case convention (src/fm_robot).
#
# The convention is not cosmetic. A package repo ships a metapackage manifest at
# its root, so colcon stops descending there and never sees the nested packages;
# every script that needs one of those reaches past the root by spelling the
# checkout path literally — setup-recorder.sh, scripts/internal/native-build.sh,
# scripts/service/appliance-update.sh all say src/fm_<name>. Under a kebab
# checkout those paths match nothing, the nested packages are never built, and
# the first report of it is a launch dying on a package it cannot find. When both
# spellings exist at once it is worse: colcon discovers the same package names
# under two prefixes and refuses to build the workspace at all.
#
# Neither failure names its cause, so name it here, at the import that produced
# it. Warning only — moving or deleting a checkout out from under someone is
# never this script's call. The fix belongs in whichever manifest wrote the
# kebab path.
# A manifest that spells a checkout path with the repo slug creates exactly the
# duplicate src/ tree warn_kebab_checkouts reports after the fact. The overlay
# manifest is the one that can still carry it: it is gitignored and copied onto a
# member's machine, so a stale copy written before the spelling was fixed
# outlives the fix in the tracked source. Catch it at the import, where the
# damage has not happened yet, and refuse — colcon aborts on the duplicate
# packages anyway, so importing is not the kinder outcome.
refuse_kebab_manifest() {  # manifest path
  local manifest="$1" bad
  [ -f "$manifest" ] || return 0
  bad="$(sed -n 's|^[[:space:]]*\(src/fm-[A-Za-z0-9-]*\):.*|\1|p' "$manifest")"
  [ -n "$bad" ] || return 0
  echo "error: $manifest spells a checkout path with the repo slug:" >&2
  while IFS= read -r line; do
    printf '         %s\n' "$line" >&2
  done <<< "$bad"
  echo "       Repos are fm-<kebab>, but a checkout under src/ is a colcon package" >&2
  echo "       tree, and colcon aborts when one repo lands under two spellings." >&2
  echo "       Use the snake form: src/fm_<name>, matching the module. A stale" >&2
  echo "       overlay manifest is regenerated by the team setup script." >&2
  return 1
}

warn_kebab_checkouts() {  # workspace root
  local root="${1:-.}" dir base snake
  for dir in "$root"/src/fm-*/; do
    # An unmatched glob stays literal, so confirm the directory before reporting.
    [ -d "$dir" ] || continue
    base="$(basename "$dir")"
    snake="${base//-/_}"
    if [ -d "$root/src/$snake" ]; then
      item "WARNING: src/$base and src/$snake are the same packages checked out twice — colcon aborts on the duplicates; keep src/$snake and remove the other"
    else
      item "WARNING: src/$base uses the repo slug — this workspace expects src/$snake, and the scripts that build its nested packages look only there"
    fi
  done
}

# Run a long command with live feedback. TTY: fork it, spin a frame + elapsed
# seconds on one \r line until it exits, then clear the line — replaying the
# captured output only on failure so a green run stays quiet and a red one is
# still debuggable. Piped (no TTY): run inline so output and errors stream
# straight through, no \r control chars in a log. Returns the command's exit.
spin() {  # label  cmd...
  local label="$1"; shift
  if [ ! -t 1 ]; then
    "$@"
    return $?
  fi
  local log; log="$(mktemp)" || return 1
  # <&0 forwards our stdin to the async job — a backgrounded command otherwise
  # gets stdin from /dev/null (POSIX), starving stdin-reading children like
  # `vcs import < manifest`.
  "$@" <&0 >"$log" 2>&1 &
  local pid=$! frames='|/-\' i=0 start=$SECONDS
  while kill -0 "$pid" 2>/dev/null; do
    printf '\r  %s %s (%ds)' "${frames:i%4:1}" "$label" "$((SECONDS - start))"
    i=$((i + 1))
    sleep 0.1
  done
  wait "$pid"; local rc=$?
  printf '\r\033[K'
  [ "$rc" -eq 0 ] || cat "$log" >&2
  rm -f "$log"
  return "$rc"
}
